version: "3.9"
services:
  master:
    image: dist_bert:latest
    build:
      context: ./
      dockerfile: Dockerfile
    command: python bert.py --gpus 1 --accelerator ddp --max_epochs 1 --num_samples 100 --num_nodes 2
    environment:
      MASTER_ADDR: "172.16.0.2"
      MASTER_PORT: 24456
      WORLD_SIZE: 2
      NODE_RANK: 0
      LOCAL_RANK: 0
    networks:
      pytorch:
        ipv4_address: 172.16.0.2
  worker:
    image: dist_bert:latest
    command: python bert.py --gpus 1 --accelerator ddp --max_epochs 1 --num_samples 100 --num_nodes 2
    environment:
      MASTER_ADDR: "172.16.0.2"
      MASTER_PORT: 24456
      WORLD_SIZE: 2
      NODE_RANK: 1
      LOCAL_RANK: 0
    depends_on:
      - master
    networks:
      pytorch:
        ipv4_address: 172.16.0.3
networks:
  pytorch:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1